name: "HiN VPN"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  HiN-VPN:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Execute PHP script
        run: |
          php base.php
          git config --global user.email "yebekhe@gmail.com"
          git config --global user.name "yebekhe"
          git config credential.helper store
          git add -A
          git commit -m "ðŸš€ Last Run - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
          git push
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          FINDIP_TOKEN: ${{ secrets.FINDIP_TOKEN }}
